#!/usr/bin/env python
# -*- coding: latin-1; py-indent-offset:4 -*-
################################################################################
# 
#   Copyright (C) 2014 Daniel Rodriguez
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
################################################################################
"""Subclass of DialogLongOp, which is generated by wxFormBuilder."""

import wx
import maingui

# Implementing DialogLongOp
class DialogLongOp(maingui.DialogLongOp):
    def __init__(self, parent, message, caption, style=wx.OK, pos=wx.DefaultPosition):
        maingui.DialogLongOp.__init__(self, parent)
        # self.m_staticTextMessage.SetLabel(message)
        self.SetTitle(caption)
        # self.GetSizer().Layout() # to ensure corrent presentation

    def OnButonClickOk(self, event):
        event.Skip()
        self.EndModal(wx.ID_OK)
